### ISSUE TITLE
database files

### ISSUE THREAD

**Issue by LingFengJ** [wschuell/repodepo#7]
Hi, I've read in readme.md that the repository contains "A ready-to-use SQLite file sqlite/rust_repos_2022_09_07_export.db" and "postgresql/data/<table>.csv CSV files (one per table) used in the import.sql script", however I am not able to find them, does it mean that the only way to get the dataset is to download the scripts and generate the dataset by myself? I'm new to database systems and Thank you in advance.

**Comment by wschuell** [comment]
Hi!
Only the metadata is to be found at https://github.com/wschuell/repo_datasets/tree/main/rust_repos_2022_09_07 .
I did not commit to the repo because it would be too big for a git repo (several GB). The actual data is on figshare: https://doi.org/10.6084/m9.figshare.c.5983534.v1 . At the bottom of the page you will find the files for 2 datasets, a sample one (only 100 repos) and the full one.
Let me know if you need more info!
